using System.Threading.Tasks;

using LiveSplit.Components.Net.Sdk.Testing;
using LiveSplit.Components.Sdk;

using NUnit.Framework;

using Verifier = LiveSplit.Components.Net.Sdk.Testing.IncrementalGeneratorVerifier<
    LiveSplit.Components.Net.Sdk.SourceGenerators.ComponentFactoryGenerator,
    LiveSplit.Components.Net.Sdk.SourceGenerators.Tests.ComponentFactoryGeneratorTest>;

namespace LiveSplit.Components.Net.Sdk.SourceGenerators.Tests;

public sealed class ComponentFactoryGeneratorTests
{
    [Test]
    public async Task VerifyGenerator()
    {
        await Verifier
            .VerifyGeneratorAsync(
                source: $$"""
                    using LiveSplit.Components.Sdk;
                    using LiveSplit.Model;
                    using LiveSplit.UI.Components;

                    namespace TestNamespace;

                    [Component(
                        Author = "John Doe",
                        Name = "Test Component",
                        Category = ComponentCategory.Other)]
                    class TestComponent
                        : LiveSplit.Components.Net.Sdk.Testing.ComponentBase
                    {
                        public TestComponent(LiveSplitState state)
                            : base(state) { }
                    }
                    """,
                expected: [(
                    "TestComponent.g.cs",
                    $$"""
                    // <auto-generated />
                    #nullable enable

                    [assembly: global::LiveSplit.UI.Components.ComponentFactoryAttribute(typeof(global::TestNamespace.TestComponentFactory))]

                    namespace TestNamespace {
                        file sealed class TestComponentFactory : global::LiveSplit.UI.Components.IComponentFactory {
                            public string ComponentName => "Test Component";
                            public string Description => "";

                            public global::LiveSplit.UI.Components.ComponentCategory Category => global::LiveSplit.UI.Components.ComponentCategory.Other;

                            public string UpdateName => "Test Component";
                            public string XMLURL => "https://github.com/John%20Doe/LiveSplit.TestComponent/changelog.xml";
                            public string UpdateURL => "https://github.com/John%20Doe/LiveSplit.TestComponent/releases/latest/download";

                            public global::LiveSplit.UI.Components.IComponent Create(global::LiveSplit.Model.LiveSplitState state) {
                                return new global::TestNamespace.TestComponent(state);
                            }
                        }
                    }
                    """)
                ])
            .ConfigureAwait(false);
    }
}

file sealed class ComponentFactoryGeneratorTest
    : IncrementalGeneratorTest<ComponentFactoryGenerator>
{
    public ComponentFactoryGeneratorTest()
    {
        AddReferenceAssembly<System.Drawing.Graphics>();
        AddReferenceAssembly<System.Windows.Forms.Form>();

        AddReferenceAssembly<UI.Components.IComponent>();
        AddReferenceAssembly<UpdateManager.IUpdateable>();

        AddReferenceAssembly<ComponentAttribute>();
        AddReferenceAssembly<ComponentBase>();
    }
}
